"""First Revision

Revision ID: 37418030d5bb
Revises: 
Create Date: 2023-05-22 12:51:58.032196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37418030d5bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Objects_description', table_name='Objects')
    op.drop_index('ix_Objects_id', table_name='Objects')
    op.drop_index('ix_Objects_owner_id', table_name='Objects')
    op.drop_index('ix_Objects_title', table_name='Objects')
    op.drop_table('Objects')
    op.drop_index('ix_books_id', table_name='books')
    op.drop_table('books')
    op.drop_table('Items')
    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Users_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Users_pkey'),
    sa.UniqueConstraint('email', name='Users_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Items',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Items_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('on_offer', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Items_pkey'),
    sa.UniqueConstraint('name', name='Items_name_key')
    )
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='books_pkey')
    )
    op.create_index('ix_books_id', 'books', ['id'], unique=False)
    op.create_table('Objects',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Objects_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['Users.id'], name='Objects_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Objects_pkey')
    )
    op.create_index('ix_Objects_title', 'Objects', ['title'], unique=False)
    op.create_index('ix_Objects_owner_id', 'Objects', ['owner_id'], unique=False)
    op.create_index('ix_Objects_id', 'Objects', ['id'], unique=False)
    op.create_index('ix_Objects_description', 'Objects', ['description'], unique=False)
    # ### end Alembic commands ###
