"""Removed index from unnecessary fields

Revision ID: d5950cb557cd
Revises: d1dcfac677a8
Create Date: 2023-05-31 18:28:31.976394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5950cb557cd'
down_revision = 'd1dcfac677a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_items_description', table_name='items')
    op.drop_index('ix_items_id', table_name='items')
    op.drop_index('ix_items_title', table_name='items')
    op.drop_table('items')
    op.alter_column('Student', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index('ix_Student_date_of_birth', table_name='Student')
    op.alter_column('StudentBookAssociation', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('StudentBookAssociation', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('StudentBookAssociation', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('StudentBookAssociation', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_Student_date_of_birth', 'Student', ['date_of_birth'], unique=False)
    op.alter_column('Student', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='items_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    op.create_index('ix_items_title', 'items', ['title'], unique=False)
    op.create_index('ix_items_id', 'items', ['id'], unique=False)
    op.create_index('ix_items_description', 'items', ['description'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
